load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "secrets.go",  #keep
    ],
    importpath = "github.com/ademuri/last-fm-tools/internal/secrets",
    visibility = ["//:__subpackages__"],
)
