load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "secrets",
    srcs = ["secrets.go"],
    importpath = "secrets",
    deps = [],
    visibility = ["//visibility:public"],
)

