load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["secrets.go"],
    importpath = "github.com/ademuri/last-fm-tools/secrets",
    visibility = ["//visibility:public"],
)
